### ISSUE TITLE
Error in JS : Editor.js:100 Uncaught TypeError: this.onChange is not a function     at Object._setXml (Editor.js:100:26)

### ISSUE THREAD

**Issue by Caroline-Prince** [Geta/geta-optimizely-sitemaps#52]
![image](https://user-images.githubusercontent.com/106403078/170770448-16d8003e-750f-4cda-9da9-4dcca4a11103.png)
I got this error when I create a page in CMS 12 and I add a picture. I press publish and the CMS will ask to publish again even if I didn't change anything. If I clic on _Compare different version_ and I open the console, I see the error _Editor.js:100 Uncaught TypeError: this.onChange is not a function
    at Object._setXml (Editor.js:100:26)_ 

My view in the CMS :
![image](https://user-images.githubusercontent.com/106403078/170770903-e4566b12-9e88-4546-84d8-d222564f5813.png)

**Comment by 1a2a3a4a** [comment]
I know it is 4 years later but did you somehow solve this? We are having the same issues now
