### ISSUE TITLE
404s on Edit, Delete and New sitemap action

### ISSUE THREAD

**Issue by petrovicnemanja** [Geta/geta-optimizely-sitemaps#92]
Encountered on version 3.1.0. Additionally, the job fails with SiteUrl null exception:

[2023-08-23 08:02:23] Information: Error on generating xml sitemap
[2023-08-23 08:02:23] Information: System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
[2023-08-23 08:02:23] Information: at System.ArgumentNullException.Throw(String paramName)
[2023-08-23 08:02:23] Information: at System.Uri..ctor(String uriString)
[2023-08-23 08:02:23] Information: at Geta.Optimizely.Sitemaps.XML.SitemapXmlGenerator.Generate(SitemapData sitemapData, Boolean persistData, Int32& entryCount)
[2023-08-23 08:02:23] Information: fail: Geta.Optimizely.Sitemaps.Controllers.GetaSitemapController[0]
[2023-08-23 08:02:23] Information: Xml sitemap data not found!
[2023-08-23 08:02:24] Information: fail: Geta.Optimizely.Sitemaps.Controllers.GetaSitemapController[0]
[2023-08-23 08:02:24] Information: Xml sitemap data not found!
 

https://github.com/Geta/geta-optimizely-sitemaps/assets/73847339/754dd226-2ef7-4f42-b141-4c6c14912d3c

**Comment by petrovicnemanja** [comment]
Fixed by updating to 3.1.1
